name: CI Checks
on:
  push:
    branches: main
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.0
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download dependencies
        run:  go get -t ./...

      - name: Test
        run:  make test
      - name: Coverage Check
        run:  make coverage
      - name: Generate Coverage Report
        run:  make report

      - name: Copy Files
        run: |
          mkdir reports
          cp coverage.html reports/.

      - name: Build
        run:  make build

      - name: Copy Files
        run: |
          mkdir artifacts
          cp api artifacts/.

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: artifacts
